### ISSUE TITLE
 Task 1: Set up Basic Backend with Spring Boot

### ISSUE THREAD

**Issue by katarinakovacova** [katarinakovacova/tasmag#1]
#### Description:
The goal of this task is to set up the basic structure of the Task Manager application using Java and Spring Boot. This includes setting up the Spring Boot project, connecting to a PostgreSQL database, and creating a basic REST endpoint to ensure that the backend is functional.

#### Subtasks:
- [x] **Create a new Spring Boot project**:
  - Use [Spring Initializr](https://start.spring.io/) to generate a new project.
  - Include the following dependencies:
    - Spring Web (for creating REST APIs)
    - Spring Data JPA (for database interaction)
    - PostgreSQL Driver (for connecting to PostgreSQL database)
    - Spring Security (for future authentication implementation)

- [x] **Set up PostgreSQL**:
  - Install PostgreSQL locally or use Docker to run a PostgreSQL instance.
  - Create a database called `task_manager`.
  - Update `application.properties` with the following:
    ```properties
    spring.datasource.url=jdbc:postgresql://localhost:5432/task_manager
    spring.datasource.username=your_username
    spring.datasource.password=your_password
    spring.jpa.hibernate.ddl-auto=update
    spring.jpa.show-sql=true
    ```

- [x] **Create a basic REST endpoint**:
  - Implement a basic `TaskController` with a simple GET endpoint that returns a test message.
  - Example:
    ```java
    @RestController
    @RequestMapping("/api/v1")
    public class TaskController {
    
        @GetMapping("/tasks")
        public ResponseEntity<String> getTasks() {
            return ResponseEntity.ok("This is the list of tasks!");
        }
    }
    ```

- [x] **Run the application**:
  - Start the application by running:
    ```bash
    ./mvnw spring-boot:run
    ```
  - Test the endpoint by running:
    ```bash
    curl http://localhost:8080/api/v1/tasks
    ```
  - Ensure the response is `"This is the list of tasks!"`.

#### Acceptance Criteria:
- [x] Spring Boot project is set up with the specified dependencies.
- [x] PostgreSQL connection is established.
- [x] A basic REST endpoint (`/api/v1/tasks`) returns a static message.
- [x] Application runs without errors and the endpoint is accessible.
